
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - workshop.mcouliba.com
  resources:
  - workshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workshop.mcouliba.com
  resources:
  - workshops/status
  verbs:
  - get
  - patch
  - update
