apiVersion: workshop.redhat-emea-ssa-team.com/v1
kind: Workshop
metadata:
  name: end-to-end-developer
  namespace: workshop-infra
spec:
  user:
    number: 5
    password: openshift
  source:
    gitURL: https://github.com/RedHat-EMEA-SSA-Team/end-to-end-developer-workshop
    gitBranch: "6.2"
  infrastructure:
    guide:
      scholars:
        enabled: true
        guideURL:
          "inner-loop" : "https://redhat-scholars.github.io/inner-loop-guide/inner-loop/6.2/index.html" 
          "outer-loop" : "https://redhat-scholars.github.io/outer-loop-guide/outer-loop/6.2/index.html" 
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: devspacesoperator.v3.1.0
      openshiftOAuth: true
    gitea:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gitea-operator
        tag: v1.2.3
    gitops:
      enabled: true
      operatorHub:
        channel: gitops-1.5
        clusterServiceVersion: openshift-gitops-operator.v1.5.3
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: pipelines-1.7
        clusterServiceVersion: openshift-pipelines-operator-rh.v1.7.2
    project:
      enabled: true
      stagingName: cn-project
    serviceMesh:
      enabled: true
      serviceMeshOperatorHub:
        channel: "stable"
        clusterServiceVersion: servicemeshoperator.v2.2.1
      elasticSearchOperatorHub:
        channel: "stable"
      jaegerOperatorHub:
        channel: "stable"
      kialiOperatorHub:
        channel: "stable"
        clusterServiceVersion: kiali-operator.v1.48.2
