apiVersion: workshop.redhat-emea-ssa-team.com/v1
kind: Workshop
metadata:
  name: end-to-end-developer
  namespace: workshop-infra
spec:
  user:
    number: 5
    password: openshift
  source:
    gitURL: https://github.com/RedHat-EMEA-SSA-Team/end-to-end-developer-workshop
    gitBranch: "6.0"
  infrastructure:
    guide:
      scholars:
        enabled: true
        guideURL:
          "inner-loop" : "https://redhat-scholars.github.io/inner-loop-guide/inner-loop/5.1/index.html" 
          "outer-loop" : "https://redhat-scholars.github.io/outer-loop-guide/outer-loop/5.1/index.html" 
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: latest
        clusterServiceVersion: crwoperator.v2.12.0
      openshiftOAuth: false
    gitea:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gitea-operator
        tag: v1.2.3
    gitops:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: openshift-gitops-operator.v1.3.0
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: redhat-openshift-pipelines.v1.5.2
    project:
      enabled: true
      stagingName: cn-project
    serviceMesh:
      enabled: true
      serviceMeshOperatorHub:
        channel: "stable"
        clusterServiceVersion: servicemeshoperator.v2.0.8
      elasticSearchOperatorHub:
        channel: "stable"
      jaegerOperatorHub:
        channel: "stable"
      kialiOperatorHub:
        channel: "stable"
        clusterServiceVersion: kiali-operator.v1.24.10
