apiVersion: workshop.redhat-emea-ssa-team.com/v1
kind: Workshop
metadata:
  name: end-to-end-developer
  namespace: workshop-infra
spec:
  user:
    number: 5
    password: openshift
  source:
    gitURL: https://github.com/RedHat-EMEA-SSA-Team/end-to-end-developer-workshop
    gitBranch: "6.1"
  infrastructure:
    guide:
      scholars:
        enabled: true
        guideURL:
          "inner-loop" : "https://redhat-scholars.github.io/inner-loop-guide/inner-loop/6.1/index.html" 
          "outer-loop" : "https://redhat-scholars.github.io/outer-loop-guide/outer-loop/6.1/index.html" 
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: tech-preview-latest-all-namespaces
        clusterServiceVersion: crwoperatorallnamespaces.v2.15.104
      openshiftOAuth: false
    gitea:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gitea-operator
        tag: v1.2.3
    gitops:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: openshift-gitops-operator.v1.4.5
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: openshift-pipelines-operator-rh.v1.6.2
    project:
      enabled: true
      stagingName: cn-project
    serviceMesh:
      enabled: true
      serviceMeshOperatorHub:
        channel: "stable"
        clusterServiceVersion: servicemeshoperator.v2.1.2
      elasticSearchOperatorHub:
        channel: "stable"
      jaegerOperatorHub:
        channel: "stable"
      kialiOperatorHub:
        channel: "stable"
        clusterServiceVersion: kiali-operator.v1.36.6
