apiVersion: workshop.mcouliba.com/v1
kind: Workshop
metadata:
  name: cloud-native-workshop
  namespace: workshop-infra
spec:
  user:
    number: 5
    password: openshift
  source:
    gitURL: https://github.com/mcouliba/cloud-native-workshop
    gitBranch: "5.0"
  infrastructure:
    argocd:
      enabled: true
      operatorHub:
        channel: alpha
        clusterServiceVersion: argocd-operator.v0.0.14
    guide:
      scholars:
        enabled: true
        guideURL: "https://redhat-scholars.github.io/inner-loop-guide/inner-loop/index.html" 
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: latest
        clusterServiceVersion: crwoperator.v2.6.0
      openshiftOAuth: false
      pluginRegistryImage:
        name: quay.io/mcouliba/che-plugin-registry
        tag: "2.5.0"
    gitea:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gitea-operator
        tag: v0.17
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: preview
        clusterServiceVersion: redhat-openshift-pipelines-operator.v1.2.3
    project:
      enabled: true
      stagingName: cn-project
    serviceMesh:
      enabled: true
      serviceMeshOperatorHub:
        channel: "stable"
        clusterServiceVersion: servicemeshoperator.v2.0.2.0
      elasticSearchOperatorHub:
        channel: "stable"
      jaegerOperatorHub:
        channel: "stable"
      kialiOperatorHub:
        channel: "stable"
        clusterServiceVersion: kiali-operator.v1.24.5
